local require=require(script.Parent.loader).load(script)
local CrateConstants=require("CrateConstants");local GetRemoteFunction=require("GetRemoteFunction");local Maid=require("Maid");local PlayerDataStoreService=require("PlayerDataStoreService");local RxPlayerUtils=require("RxPlayerUtils")
local S={ServiceName="CrateService"};local COOLDOWN=8;local ATTR="CrateService_CrateCooldown";local SUBSTORE="Colors"
function S:Init(b)self._maid=Maid.new();self._playerDataStoreService=b:GetService(PlayerDataStoreService)end
function S:Start()self._maid:GiveTask(RxPlayerUtils.observePlayersBrio():Subscribe(function(brio)self:_handlePlayer(brio:ToMaidAndValue())end));local remote=GetRemoteFunction("CrateServiceRemoteFunction");remote.OnServerInvoke=function(player,msg)if msg~="Unbox" then return end;local prev=player:GetAttribute(ATTR);local now=workspace:GetServerTimeNow();if prev and now-prev<COOLDOWN then return end;player:SetAttribute(ATTR,now);local idx=math.random(1,#CrateConstants);self:_awardColor(player,idx);return idx end;self._maid:GiveTask(function()remote.OnServerInvoke=nil end)end
local function setKey(parent,key,value)local r=parent:FindFirstChild(key);if value==nil then if r then r:Destroy()end return end;if r then r.Value=value else r=Instance.new("IntValue");r.Name=key;r.Archivable=false;r.Value=value;r.Parent=parent end end
function S:_handlePlayer(maid,player)maid:GivePromise(self._playerDataStoreService:PromiseDataStore(player)):Then(function(root)local repr=Instance.new("Folder");repr.Archivable=false;repr.Name="ColorInventory";repr.Parent=player;local store=root:GetSubStore(SUBSTORE);local last=nil;maid:GiveTask(store:Observe():Subscribe(function(snapshot)local delta=store._computeChangedKeys(nil,last,snapshot);for key in delta do setKey(repr,key,snapshot[key])end;last=snapshot end))end)end
function S:_awardColor(player,index)return self._playerDataStoreService:PromiseDataStore(player):Then(function(root)local store=root:GetSubStore(SUBSTORE);return store:Load(tostring(index),0):Then(function(count)store:Store(tostring(index),count+1)end)end)end
function S:Destroy()self._maid:DoCleaning()end
return S
