local require=require(script.Parent.loader).load(script)
local BasicPaneUtils=require("BasicPaneUtils"); local ColorRngScreenProvider=require("ColorRngScreenProvider"); local CrateControlsService=require("CrateControlsService"); local CrateInventoryButton=require("CrateInventoryButton"); local CrateInventoryView=require("CrateInventoryView"); local CrateServiceClient=require("CrateServiceClient"); local GameScalingUtils=require("GameScalingUtils"); local Maid=require("Maid"); local Rx=require("Rx"); local StateStack=require("StateStack"); local ValueObject=require("ValueObject")
local S={ServiceName="CrateInventoryService"}
function S:Init(b) self._maid=Maid.new(); self._crateControlsService=b:GetService(CrateControlsService); self._crateServiceClient=b:GetService(CrateServiceClient); self._colorRngScreenProvider=b:GetService(ColorRngScreenProvider); self._enabled=self._maid:Add(StateStack.new(false)); self._inventoryOpen=self._maid:Add(ValueObject.new(false)) end
function S:PushEnabled() return self._enabled:PushState(true) end
function S:Start() self._maid:GiveTask(self._crateControlsService.AnimationActive.Changed:Connect(function(a) if a then self._inventoryOpen.Value=false end end)); self._maid:GiveTask(self._enabled:Observe():Pipe({BasicPaneUtils.whenVisibleBrio(function(m)return self:_mountSidebar(m) end)}):Subscribe()); self._maid:GiveTask(Rx.combineLatest({a=self._enabled:Observe(),b=self._inventoryOpen:Observe()}):Pipe({Rx.map(function(s)return s.a and s.b end),Rx.distinct(),BasicPaneUtils.whenVisibleBrio(function(m)return self:_mountInventory(m) end)}):Subscribe()) end
function S:_screen(m) local s=self._colorRngScreenProvider:Get("CRATEINVENTORY"); s.IgnoreGuiInset=true; m:GiveTask(GameScalingUtils.renderDialogPadding({ScreenGui=s,Parent=s}):Subscribe()); m:GiveTask(s); return s end
function S:_mountSidebar(m) local s=self:_screen(m); local b=CrateInventoryButton.new(); b.Gui.AnchorPoint=Vector2.new(0,.5); b.Gui.Position=UDim2.fromScale(0,.5); b.Gui.Parent=s; m:GiveTask(GameScalingUtils.renderUIScale({ScreenGui=s,Parent=b.Gui}):Subscribe()); m:GiveTask(self._inventoryOpen:Mount(b.State)); m:GiveTask(self._inventoryOpen.Changed:Connect(function(v)b.State.Value=v end)); m:GiveTask(b); return b end
function S:_mountInventory(m) local s=self:_screen(m); local v=CrateInventoryView.new(self._crateServiceClient:GetModel()); v.Gui.AnchorPoint=Vector2.new(.5,.5); v.Gui.Position=UDim2.fromScale(.5,.5); v.Gui.Parent=s; m:GiveTask(GameScalingUtils.renderUIScale({ScreenGui=s,Parent=v.Gui}):Subscribe()); m:GiveTask(v.OnClose:Connect(function()self._inventoryOpen.Value=false end)); m:GiveTask(v); return v end
function S:Destroy()self._maid:DoCleaning()end
return S
