local require=require(script.Parent.loader).load(script)
local Players=game:GetService("Players")
local BasicPaneUtils=require("BasicPaneUtils"); local CameraStackService=require("CameraStackService"); local CharacterUtils=require("CharacterUtils"); local ColorRngScreenProvider=require("ColorRngScreenProvider"); local CoreGuiEnabler=require("CoreGuiEnabler"); local CrateAnimUtils=require("CrateAnimUtils"); local CrateButton=require("CrateButton"); local CrateConstants=require("CrateConstants"); local CrateServiceClient=require("CrateServiceClient"); local GameScalingUtils=require("GameScalingUtils"); local Maid=require("Maid"); local Signal=require("Signal"); local SpringObject=require("SpringObject"); local StateStack=require("StateStack")
local S={ServiceName="CrateControlsService"}
function S:Init(b) self._serviceBag=b; self._maid=Maid.new(); self._colorRngScreenProvider=b:GetService(ColorRngScreenProvider); self._crateService=b:GetService(CrateServiceClient); self._coreGuiEnabler=b:GetService(CoreGuiEnabler); self._cameraStackService=b:GetService(CameraStackService); self._enabled=self._maid:Add(StateStack.new(false,"boolean")); self._unboxed=self._maid:Add(Signal.new()); self.AnimationActive=self._maid:Add(StateStack.new(false)) end
function S:PushEnabled() return self._enabled:PushState(true) end
function S:Start() self._maid:GiveTask(self._enabled:Observe():Pipe({BasicPaneUtils.whenVisibleBrio(function(m)return self:_makeButton(m) end)}):Subscribe()); self._maid:Add(CrateAnimUtils.promisePreload()):Then(function() self:_mountAnim(self._maid); self:_mountLight(self._maid); self:_mountShake(self._maid) end) end
function S:_makeButton(m) local screen=self._colorRngScreenProvider:Get("CRATECONTROL"); screen.IgnoreGuiInset=true; m:GiveTask(GameScalingUtils.renderDialogPadding({ScreenGui=screen,Parent=screen}):Subscribe()); m:GiveTask(screen); local btn=CrateButton.new(); btn.Gui.AnchorPoint=Vector2.new(.5,1); btn.Gui.Position=UDim2.fromScale(.5,1); btn.Gui.Parent=screen; m:GiveTask(GameScalingUtils.renderUIScale({ScreenGui=screen,Parent=btn.Gui}):Subscribe()); m:GiveTask(btn.Activated:Connect(function() m._prom=self._crateService:PromiseTryUnbox(); m._prom:Then(function(i) if i then self._unboxed:Fire(i) end end) end)); m:GiveTask(btn); return btn end
function S:_mountAnim(m) local screen=self._colorRngScreenProvider:Get("CRATEUNBOX"); screen.IgnoreGuiInset=true; m:GiveTask(screen); local proxy=Instance.new("Frame"); proxy.Size=UDim2.fromScale(1,1); proxy.AnchorPoint=Vector2.new(.5,.5); proxy.Position=UDim2.fromScale(.5,.5); proxy.BackgroundTransparency=1; proxy.Parent=screen; m:GiveTask(GameScalingUtils.renderUIScale({ScreenGui=screen,Parent=proxy}):Subscribe()); m:GiveTask(proxy); m:GiveTask(self._unboxed:Connect(function(i) m._anim=CrateAnimUtils.animate(proxy,i); m._hideGui=self._coreGuiEnabler:Disable(newproxy(),Enum.CoreGuiType.All); m._state=self.AnimationActive:PushState(true); m._anim:Finally(function() m._hideGui=nil; m._state=false end) end)) end
function S:_mountLight(m) local l=Instance.new("PointLight"); l.Name="CrateLight"; l.Shadows=true; l.Range=48; l.Brightness=0; m:GiveTask(l); local spring=SpringObject.new(0,3,1); m:GiveTask(spring:ObserveRenderStepped():Subscribe(function(f) l.Brightness=f*.3; l.Enabled=f>.01 end)); m:GiveTask(spring); m:GiveTask(self._unboxed:Connect(function(i) m._light=task.delay(CrateAnimUtils.ESTIMATED_TIME_REVEAL,function() local hrp=CharacterUtils.getAlivePlayerRootPart(Players.LocalPlayer); l.Parent=hrp; l.Color=CrateConstants[i].Color; spring.Position=1 end) end)) end
function S:_mountShake(m) m:GiveTask(self._unboxed:Connect(function(i) m._shake=task.delay(CrateAnimUtils.ESTIMATED_TIME_REVEAL,function() self._cameraStackService:GetImpulseCamera():ImpulseRandom(Vector3.one*.25*math.pow(2,CrateConstants[i].Tier)) end) end)) end
function S:Destroy() self._maid:DoCleaning() end
return S
